export const LOAD_NEW_CAPTCHA_START = 'LOAD_NEW_CAPTCHA_START';
export const LOAD_NEW_CAPTCHA_SUCCESS = 'LOAD_NEW_CAPTCHA_SUCCESS';
export const LOAD_NEW_CAPTCHA_FAIL = 'LOAD_NEW_CAPTCHA_FAIL';
export const RESET_LOAD_NEW_CAPTCHA = 'RESET_LOAD_NEW_CAPTCHA';

export const RELOAD_NEW_CAPTCHA_START = 'RELOAD_NEW_CAPTCHA_START';
export const RELOAD_NEW_CAPTCHA_SUCCESS = 'RELOAD_NEW_CAPTCHA_SUCCESS';
export const RELOAD_NEW_CAPTCHA_FAIL = 'RELOAD_NEW_CAPTCHA_FAIL';
export const RESET_RELOAD_NEW_CAPTCHA = 'RESET_RELOAD_NEW_CAPTCHA';

export const SUBMIT_CAPTCHA_START = 'SUBMIT_CAPTCHA_START';
export const SUBMIT_CAPTCHA_SUCCESS = 'SUBMIT_CAPTCHA_SUCCESS';
export const SUBMIT_CAPTCHA_FAIL = 'SUBMIT_CAPTCHA_FAIL';
export const RESET_SUBMIT_CAPTCHA = 'RESET_SUBMIT_CAPTCHA';
